Repository FIS2425/payment-svc, pull requests merged in 2024-11, with the labels that each got.

#11 Feature/04 get clinic
  .env.example
  .github/CODEOWNERS
  docker-compose.yml
  openapi.yaml
  package-lock.json
  package.json
  populators/ClinicPopulator.js
  src/api.js
  src/controllers/clinicController.js
  src/routes/clinicRoute.js
  src/schemas/Clinic.js
  tests/sample.test.js
Labels: 🧪 Tests, 😎 size/m, ⚙️ Configuration, 🏠 Github Configuration, 📦 Dependencies, 🐳 Build

#13 upload of getAllClinics
  src/controllers/clinicController.js
Labels: size/s

#14 Update clinicController.js with the update of a clinic
  src/controllers/clinicController.js
Labels: size/s

#15 Update clinicController.js with de delete and deactivation of a clinic
  src/controllers/clinicController.js
Labels: size/s

#17 creation of Payments
  src/api.js
  src/controllers/paymentController.js
  src/routes/paymentRoute.js
  src/schemas/Payment.js
Labels: size/s

#19 upload of the get payments functionality
  src/controllers/paymentController.js
Labels: size/s

#21 Feature/20 delete payment
  src/controllers/paymentController.js
Labels: size/s

#25 feat: implement Circuit Breaker
  src/controllers/clinicController.js
  src/controllers/paymentController.js
Labels: 😎 size/m

#24 [Feat] creation of test
  tests/integration/controllers/clinicController.test.js
Labels: 🧪 Tests, 😎 size/m

#26 PAYMENT SERVICE
  .env.example
  Dockerfile
  docker-compose.yml
  openapi.yaml
  package-lock.json
  package.json
  populators/ClinicPopulator.js
  populators/PlanPopulator.js
  src/api.js
  src/config/stripeConfig.js
  src/controllers/paymentController.js
  src/controllers/planController.js
  src/routes/paymentRoute.js
  src/routes/planRoute.js
  src/schemas/Plan.js
Labels: 😎 size/m, ⚙️ Configuration, 📦 Dependencies, 🐳 Build

#28 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 🏠 Github Configuration, size/xs

#29 chore: update environment variables and change server port to 3003
  .env.example
  docker-compose.yml
  openapi.yaml
  package-lock.json
  package.json
  src/config/index.js
Labels: size/xs

#31 Merge develop into main
  .env.example
  .github/workflows/docker-deploy.yml
  Dockerfile
  docker-compose.yml
  openapi.md
  openapi.yaml
  package-lock.json
  package.json
  populators/ClinicPopulator.js
  populators/PlanPopulator.js
  src/api.js
  src/config/index.js
  src/config/stripeConfig.js
  src/controllers/clinicController.js
  src/controllers/paymentController.js
  src/controllers/planController.js
  src/routes/clinicRoute.js
  src/routes/paymentRoute.js
  src/routes/planRoute.js
  src/schemas/Clinic.js
  src/schemas/Payment.js
  src/schemas/Plan.js
  tests/integration/controllers/clinicController.test.js
  tests/sample.test.js
Labels: 🧪 Tests, 🤯 size/xl, ⚙️ Configuration, 🚀 CI/CD, 📦 Dependencies, 🐳 Build

#33 Updating develop
  .github/CODEOWNERS
  .github/workflows/docker-deploy.yml
  openapi.md
  package-lock.json
  package.json
Labels: 🏠 Github Configuration, 🚀 CI/CD, 📦 Dependencies, size/s

#34 chore: update environment variables and docker-compose configuration;…
  .env.example
  docker-compose.yml
  openapi.yaml
  package-lock.json
  populators/ClinicPopulator.js
Labels: ⚙️ Configuration, 📦 Dependencies, size/s, 🐳 Build
