Repository FIS2425/payment-svc, pull requests merged in 2025-01, with the labels that each got.

#58 Fix openapi
  openapi.yaml
Labels: size/xs

#59 v1.2.2
  package-lock.json
  package.json
  populators/Clinic.js
  populators/Plan.js
  populators/runPopulator.js
  src/config/logger.js
  src/controllers/clinicController.js
  tests/integration/controllers/clinicController.test.js
  tests/setup/setup.js
Labels: 🧪 Tests, 😎 size/m, 📦 Dependencies

#61 Fix/populator fix
  openapi.md
  openapi.yaml
  populators/Clinic.js
  populators/Plan.js
  src/controllers/planController.js
  src/routes/planRoute.js
Labels: size/s

#62 v1.2.3
  openapi.md
  openapi.yaml
  populators/Clinic.js
  populators/Plan.js
  src/controllers/planController.js
  src/middleware/verifyAuth.js
  src/routes/planRoute.js
Labels: size/s

#64 Feature/63 get allpayments
  openapi.yaml
  populators/Clinic.js
  populators/Payment.js
  populators/Plan.js
  src/controllers/paymentController.js
  src/routes/paymentRoute.js
Labels: 😎 size/m

#70 1.2.7
  package-lock.json
  package.json
  populators/Plan.js
Labels: 📦 Dependencies, size/xs

#73 fix: added new tests
  tests/integration/controllers/clinicController.test.js
Labels: 🧪 Tests, size/s
